all: clean lab6-2 lab6-3 lab6-4

lab6-2: lab6-2.cpp
	g++ -pthread -o lab6-2 lab6-2.cpp
lab6-3: lab6-3.cpp
	g++ -pthread -o lab6-3 lab6-3.cpp
lab6-4: lab6-4.cpp
	g++ -pthread -o lab6-4 lab6-4.cpp

clean:
	rm -rf *.o lab6-2 lab6-3 lab6-4